run_name: OLMo-small
seed: 6198
dry_run: false

wandb:
  name: ${run_name}
  project: olmo-small

# 模型配置
model:
  d_model: 512         # 从2048减小到512
  n_heads: 8           # 从16减小到8
  n_layers: 8          # 从16减小到8
  mlp_ratio: 4         # 从8减小到4
  weight_tying: true
  alibi: false
  rope: true
  flash_attention: true  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 1024  # 从2048减小到1024
  vocab_size: 151644
  embedding_size: 151648
  eos_token_id: 151643  # Qwen tokenizer
  pad_token_id: 151643  # Qwen tokenizer
  init_device: meta
  init_fn: mitchell

compile: ##null  # causes instability on AMD GPUs
  backend: inductor

# 优化器配置
optimizer:
  name: adamw
  learning_rate: 6.0e-4  # 增加学习率以加速训练
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 1000        # 减少预热步数
  alpha_f: 0.1

# tokenizer配置
tokenizer:
  name_or_path: "Qwen/Qwen2.5-0.5B"
  truncate_direction: right

# checkpoint保存配置
save_folder: ${path.choose:${oc.env:SCRATCH_DIR,no_exist}/checkpoints,/results}/${oc.env:SLURM_JOB_ID,${run_name}}
save_overwrite: false
# Sharded checkpoints (best for restarts)
save_interval: 200
save_num_checkpoints_to_keep: 3  # 减少保存的检查点数量
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 5000    # 增加保存间隔
save_num_unsharded_checkpoints_to_keep: 1  # 只保留最新的检查点

# checkpoint加载路径
load_path: null

# 训练步数及batchsize
max_duration: 10000     # 显著减少训练步数
global_train_batch_size: 512   # 减小全局批量大小
device_train_microbatch_size: 8  # 减小设备批量大小

precision: amp_bf16

fsdp:
  wrapping_strategy: null
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

# 训练时长
time_limit: 10800  # 3小时 = 10800秒

# 移除验证集和测试集
eval_interval: -1  # 禁用验证
eval_subset_num_batches: 0
device_eval_batch_size: ${device_train_microbatch_size}
evaluators: []  # 空列表，不进行评估

# 训练数据位置
data:
  pad_direction: right
  num_workers: 0
  drop_last: true
  pin_memory: true
  prefetch_factor: 8  # 从16减小到8
  persistent_workers: true
  timeout: 0
  paths:
    # 使用本地数据文件
    - /mnt/Jianfeng/olmo_npy/RefinedWeb/part-0-00000.npy
    - /mnt/Jianfeng/olmo_npy/RefinedWeb/part-0-00001.npy
    - /mnt/Jianfeng/olmo_npy/RefinedWeb/part-1-00000.npy
    - /mnt/Jianfeng/olmo_npy/RefinedWeb/part-1-00002.npy
